services:
  backend:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/annotations

  frontend:
    build: ./annotation-tool
    ports:
      - "3000:80"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
